# Generated by Django 5.1.2 on 2024-11-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
