# Generated by Django 5.1.2 on 2024-11-04 18:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0006_alter_banner_image_alter_personalinfo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('portfolio', 'Portfolio')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
