# Generated by Django 5.1.2 on 2024-11-20 17:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0007_banner_alt_text_banner_page_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='resume'),
        ),
    ]
